[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pica-suite"
version = "1.0.3"
authors = [
  { name="Prathamesh Deshmukh", email="pdeshmukh@csr.res.in" },
  { name="Sudip Mukherjee", email="sudipm@csr.res.in" },
]
description = "PICA: Advanced High-Precision Transport Measurement Automation with Python"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [ # Pinned to match requirements.txt for stability
    "numpy>=1.22.4",
    "pandas>=1.4.2",
    "matplotlib>=3.5.2",
    "PyVISA>=1.12.0",
    "PyMeasure>=0.10.0",
    "pyvisa-py>=0.5.3",
    "scipy",
    "Pillow>=10.3.0",
    "psutil>=5.9.8",
    "zeroconf>=0.113.0"
]

[project.optional-dependencies]
gpib = ["gpib-ctypes>=0.3.0"]

[project.urls]
"Homepage" = "https://github.com/prathameshnium/PICA-Python-Instrument-Control-and-Automation"
"Bug Tracker" = "https://github.com/prathameshnium/PICA-Python-Instrument-Control-and-Automation/issues"

# This finds the new 'pica' folder automatically
[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pica*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
pythonpath = [
    ".",
]

[project.scripts]
pica-gui = "pica.main:main"
pica-cli = "pica.cli:main"
