[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pica-suite"
version = "1.0.1"
authors = [
  { name="Prathamesh Deshmukh", email="prathamesh.deshmukh@example.com" },
  { name="Sudip Mukherjee", email="sudipm@csr.res.in" },
]
description = "Python-based Instrument Control and Automation Suite"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Topic :: Scientific/Engineering :: Physics",
]
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "PyVISA",
    "PyMeasure",
    "pyvisa-py",
    "scipy"
]

[project.urls]
"Homepage" = "https://github.com/prathameshnium/PICA-Python-Instrument-Control-and-Automation"
"Bug Tracker" = "https://github.com/prathameshnium/PICA-Python-Instrument-Control-and-Automation/issues"

# This finds the new 'pica' folder automatically
[tool.setuptools.packages.find]
where = ["."]
include = ["pica*"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
pythonpath = [
    ".",
]