name: Build Python Executable

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed PICA_Launcher_V4.py

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/PICA_Launcher_V4.exe
          asset_name: PICA_Launcher_V4-Windows-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true
