# This workflow builds a standalone Python executable for Windows using Nuitka
# and attaches it to a new GitHub Release.

name: Build Python Executable with Nuitka

on:
  release:
    types: [created] # This workflow runs automatically whenever a new release is published.

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Required to write the release asset.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          
          # --- FINAL CORRECTED CONFIGURATION ---

          # This is the corrected input name to specify the MSVC compiler.
          msvc: 'latest'

          # Enable plugins for GUI and scientific libraries.
          enable-plugins: "qt-binding,numpy"

          # Pass Nuitka command-line arguments.
          script-name: PICA_Launcher_V4.py --onefile

          # Hide the console window.
          disable-console: true
          
          # Set the application icon.
          windows-icon-from-ico: _assets/LOGO/UGC_DAE_CSR.ico
          
          # Include necessary data directories.
          include-data-dir: |
            _assets=_assets
            Delta_mode=Delta_mode
            Keithley_2400=Keithley_2400
            Keithley_2400_Keithley_2182=Keithley_2400_Keithley_2182
            Keithley_6517B=Keithley_6517B
            LCR_Keysight_E4980A=LCR_Keysight_E4980A
            Lakeshore_350_340=Lakeshore_350_340
            Lock_in_amplifier=Lock_in_amplifier
            Utilities=Utilities

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Nuitka's --onefile mode creates a .dist folder for the output.
          file: PICA_Launcher_V4.dist/PICA_Launcher_V4.exe
          asset_name: PICA_Launcher-Windows-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true

