# This workflow builds a standalone Python executable for Windows using Nuitka
# and attaches it to a new GitHub Release.

name: Build Python Executable with Nuitka

on:
  release:
    types: [created] # This workflow runs automatically whenever a new release is published.

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Required to write the release asset.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # Using a requirements file with pinned numpy and explicit PySide6 is crucial for stability.
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        # --- THE FINAL, VERIFIED CONFIGURATION ---
        # Use the standard and stable major version tag '@v0'. This is the correct way.
        uses: Nuitka/Nuitka-Action@v0
        with:
          # Lock Nuitka to a recent, known-stable version.
          nuitka-version: '2.6'
          
          # This ensures Nuitka finds and uses the MSVC compiler.
          msvc: 'latest'

          # Modern Nuitka auto-detects Qt usage. The other plugins are still necessary.
          enable-plugins: "numpy,pandas,tk-inter"

          # Pass Nuitka command-line arguments.
          script-name: PICA_Launcher_V4.py --onefile

          # Hide the console window.
          disable-console: true
          
          # Set the application icon.
          windows-icon-from-ico: _assets/LOGO/UGC_DAE_CSR.ico
          
          # Include necessary data directories.
          include-data-dir: |
            _assets=_assets
            Delta_mode=Delta_mode
            Keithley_2400=Keithley_2400
            Keithley_2400_Keithley_2182=Keithley_2400_Keithley_2182
            Keithley_6517B=Keithley_6517B
            LCR_Keysight_E4980A=LCR_Keysight_E4980A
            Lakeshore_350_340=Lakeshore_350_340
            Lock_in_amplifier=Lock_in_amplifier
            Utilities=Utilities

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: PICA_Launcher_V4.dist/PICA_Launcher_V4.exe
          asset_name: PICA_Launcher-Windows-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true

