name: Build Python Executable with Nuitka

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: PICA_Launcher_V4.py
          standalone: true
          onefile: true
          windows-disable-console: true
          windows-icon-from-ico: _assets/LOGO/UGC_DAE_CSR.ico
          # Include all necessary data and script folders
          include-data-dir: |
            _assets
            Delta_mode
            Keithley_2400
            Keithley_2400_Keithley_2182
            Keithley_6517B
            LCR_Keysight_E4980A
            Lakeshore_350_340
            Lock_in_amplifier
            Utilities

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # Nuitka places the final .exe in the 'build' directory
          file: build/PICA_Launcher_V4.exe
          asset_name: PICA_Launcher-Windows-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true
