# This workflow builds a standalone Python executable for Windows using Nuitka
# and attaches it to a new GitHub Release.

name: Build Python Executable with Nuitka

on:
  release:
    types: [created] # This workflow runs automatically whenever a new release is published.

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write # Required to write the release asset.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        # A stable requirements file is the foundation of a reliable build.
        run: pip install -r requirements.txt

      - name: Build with Nuitka
        # --- THE FINAL, VERIFIED CONFIGURATION ---
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: '2.6'
          msvc: 'latest'
          enable-plugins: "numpy,tk-inter"
          
          # --- CORRECTED SYNTAX BELOW ---
          # Provide the script name ONLY.
          script-name: PICA_Launcher_V4.py

          # Use the 'deployment' flag. On Windows, this implies a one-file build.
          deployment: true

          # Action-specific inputs remain separate.
          disable-console: true
          windows-icon-from-ico: _assets/LOGO/UGC_DAE_CSR.ico
          include-data-dir: |
            _assets=_assets
            Delta_mode=Delta_mode
            Keithley_2400=Keithley_2400
            Keithley_2400_Keithley_2182=Keithley_2400_Keithley_2182
            Keithley_6517B=Keithley_6517B
            LCR_Keysight_E4980A=LCR_Keysight_E4980A
            Lakeshore_350_340=Lakeshore_350_340
            Lock_in_amplifier=Lock_in_amplifier
            Utilities=Utilities

      - name: Upload Executable to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          # The output is now in the root of the repo by default with --deployment
          file: PICA_Launcher_V4.exe
          asset_name: PICA_Launcher-Windows-${{ github.ref_name }}.exe
          tag: ${{ github.ref }}
          overwrite: true

